### ISSUE TITLE
NoMethodError: undefined method `bulk_requeue' for Sidekiq::BasicFetch:Class

### ISSUE THREAD

**Issue by mateusluizfb** [brainopia/sidekiq-limit_fetch#110]
This was my [original](https://github.com/mperham/sidekiq/issues/4621) issue, I thought it was a sidekiq bug, but it was answered that was a `sidekiq-limit_fetch` issue. 
 
Ruby version: 2.6.4
Sidekiq / Pro / Enterprise version(s): 6.1.0

Please include your initializer and any error message with the full backtrace.

```
Interrupt: Interrupt
  from sidekiq/cli.rb:152:in `block in <class:CLI>'
  from sidekiq/cli.rb:173:in `handle_signal'
  from sidekiq/cli.rb:98:in `launch'
  from sidekiq/cli.rb:83:in `run'
  from bundle/ruby/2.6.0/gems/sidekiq-6.1.0/bin/sidekiq:31:in `<top (required)>'
  from bundle/ruby/2.6.0/bin/sidekiq:23:in `load'
  from bundle/ruby/2.6.0/bin/sidekiq:23:in `<top (required)>'
  from bundler/cli/exec.rb:74:in `load'
  from bundler/cli/exec.rb:74:in `kernel_load'
  from bundler/cli/exec.rb:28:in `run'
  from bundler/cli.rb:463:in `exec'
  from bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  from bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  from bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  from bundler/cli.rb:27:in `dispatch'
  from bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  from bundler/cli.rb:18:in `start'
  from bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
  from bundler/friendly_errors.rb:124:in `with_friendly_errors'
  from bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
  from bin/bundle:104:in `load'
  from bin/bundle:104:in `<main>'
NoMethodError: undefined method `bulk_requeue' for Sidekiq::BasicFetch:Class
  from sidekiq/limit_fetch.rb:30:in `bulk_requeue'
  from sidekiq/launcher.rb:61:in `stop'
  from sidekiq/cron/launcher.rb:36:in `stop'
  from sidekiq/cli.rb:102:in `rescue in launch'
  from sidekiq/cli.rb:93:in `launch'
  from sidekiq/cli.rb:83:in `run'
  from bundle/ruby/2.6.0/gems/sidekiq-6.1.0/bin/sidekiq:31:in `<top (required)>'
  from bundle/ruby/2.6.0/bin/sidekiq:23:in `load'
  from bundle/ruby/2.6.0/bin/sidekiq:23:in `<top (required)>'
  from bundler/cli/exec.rb:74:in `load'
  from bundler/cli/exec.rb:74:in `kernel_load'
  from bundler/cli/exec.rb:28:in `run'
  from bundler/cli.rb:463:in `exec'
  from bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  from bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
  from bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
  from bundler/cli.rb:27:in `dispatch'
  from bundler/vendor/thor/lib/thor/base.rb:466:in `start'
  from bundler/cli.rb:18:in `start'
  from bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:30:in `block in <top (required)>'
  from bundler/friendly_errors.rb:124:in `with_friendly_errors'
  from bundle/ruby/2.6.0/gems/bundler-1.17.3/exe/bundle:22:in `<top (required)>'
  from bin/bundle:104:in `load'
  from bin/bundle:104:in `<main>'
ADDITIONAL DATA
```

Are you using an old version? No
Have you checked the changelogs to see if your issue has been fixed in a later version? Yes

https://github.com/mperham/sidekiq/blob/master/Changes.md
https://github.com/mperham/sidekiq/blob/master/Pro-Changes.md
https://github.com/mperham/sidekiq/blob/master/Ent-Changes.md

**Comment by leoarnold** [comment]
The method `bulk_requeue` changed from class method to instance method in https://github.com/mperham/sidekiq/pull/4602/

**Comment by pomartel** [comment]
@mateusluizfb Did you close the issue because there is a fix? I also run into this issue.

**Comment by pcraston** [comment]
@mateusluizfb I'd also be keen to hear why you closed this issue. I'm still seeing it with sidekiq 6.1.1

**Comment by vinc** [comment]
+1 same issue here after upgrading sidekiq from 6.1.0 to 6.1.1

**Comment by lucaszunder** [comment]
@mateusluizfb we have the same issue even after upgrading to 5.11

**Comment by ojsdude** [comment]
+1 I am still having the same issue when using `sidekiq -> 6.2.1` with `sidekiq-limit_fetch -> 3.4.0` on a heroku rails environment

```
Message: undefined method `bulk_requeue' for Sidekiq::BasicFetch:Class
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-limit_fetch-3.4.0/lib/sidekiq/limit_fetch.rb:30 bulk_requeue
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/manager.rb:127 hard_shutdown
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/manager.rb:80 stop
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/launcher.rb:56 stop
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/cli.rb:116 rescue in launch
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/cli.rb:107 launch
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/lib/sidekiq/cli.rb:97 run
/app/vendor/bundle/ruby/2.7.0/gems/sidekiq-6.2.1/bin/sidekiq:31 <top (required)>
/app/vendor/bundle/ruby/2.7.0/bin/sidekiq:23 load
/app/vendor/bundle/ruby/2.7.0/bin/sidekiq:23 <top (required)>
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/cli/exec.rb:63 load
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/cli/exec.rb:63 kernel_load
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/cli/exec.rb:28 run
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/cli.rb:474 exec
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/command.rb:27 run
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/invocation.rb:127 invoke_command
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor.rb:392 dispatch
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/cli.rb:30 dispatch
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/vendor/thor/lib/thor/base.rb:485 start
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/cli.rb:24 start
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/exe/bundle:49 block<top (required)>
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/lib/bundler/friendly_errors.rb:128 with_friendly_errors
/app/vendor/bundle/ruby/2.7.0/gems/bundler-2.2.21/exe/bundle:37 <top (required)>
/app/bin/bundle:104 load
/app/bin/bundle:104 <main>
```
